- name: Launch backend container
  docker_container:
    name: app
    image: venujadesilva/tp-devops-backend:latest
    state: started
    pull: yes
    restart_policy: always
    env:
      DATABASE_HOST: database
      DATABASE_PASSWORD: pwd
    networks:
      - name: app-network
